[project]
name = "nfl-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "gunicorn>=23.0.0",
    "requests>=2.32.4",
]
